### ISSUE TITLE
Can't install nethserver-messaging with nethserver-dc

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5052]
Reference:
http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/2

yum install @nethserver-messaging
...
Error: nethserver-dc conflicts with nethserver-directory-3.0.0-1.ns7.noarch

**Comment by gsanchietti** [comment]
Removed LDAP-specific implementation.
The package can now be installed with nethserver-directory or nethserver-dc.

**Note**: if nethserver-directory or nethserver-dc are installed after nethserver-ejabberd, the admin must reconfigure ejabberd executing the command: `signal-event nethserver-ejabberd-update`.

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-ejabberd-1.1.0-1.3.g3413250.ns7.noarch.rpm

*Test case 1*
* Install nethserver-dc and create a user
* Install nethserver-ejabberd
* Try to access ejabberd using the created user

*Test case 2*
* Install nethserver-directory and create a user
* Install nethserver-ejabberd
* Try to access ejabberd using the created user

**Comment by filippocarletti** [comment]
In the same system where yum install @nethserver-messaging failed, the command
`yum --enablerepo=nethserver-testing install nethserver-ejabberd`
succeeded.

**Comment by filippocarletti** [comment]
My jabber client can't connect to the server. In ejabberd.log I read:
2016-07-19 12:18:25.653 [warning] <0.300.0>@eldap:report_bind_failure:1007 LDAP bind failed on nsdc-ns7b1.neth.net:389
Reason: strongAuthRequired

**Comment by gsanchietti** [comment]
> Reason: strongAuthRequired

Beside this error, which must be addressed in other ways, does this fix resolve the current issue?

**Comment by filippocarletti** [comment]
The updated package resolves the installation problem.
The workaround provided in #5067 solves the xmpp client connection problem.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-ejabberd-1.1.1-1.ns7.noarch.rpm

**Comment by snao1** [comment]
I still have the problem:

> [warning] <0.300.0>@eldap:report_bind_failure:1007 LDAP bind failed on ser.ver.lan:389
Reason: strongAuthRequired

anyone fixed it? Nethserver is last version, fresh install, all updates. Succefully joined a samba domain and correctly showing users

**Comment by gsanchietti** [comment]
These are two different problems.
Please report your issue to https://community.nethserver.org/ :)
